FROM openjdk:21
VOLUME /tmp
ADD java21-poc-0.0.1-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
#ENV JAVA_TOOL_OPTIONS "-javaagent:/pointer/rekyc-apm/smotlapm.jar"
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]